### ISSUE TITLE
(질문)Text 파일은 어떤 확장자로 받을까요??

### ISSUE THREAD

**Issue by rep87** [dre4m1ng/emotional_reading#2]
Project gutenberg(프로젝트 구텐베르크)라는 사이트에 저작권이 지난 책이 올라오고, 오디오북도 있으면 올라오더라고요.

전부 살펴본 건 아니지만

Text는
EPUB3(신형 E북리더기가 읽는 저장 방식)
EPUB(구형 E북리더기)
Kindle(애플 기기가 읽는 방식)
older Kindles(구형 애플 기기)
Plain Text UTF-8(그냥 쌩 텍스트 제공)

일단은 Plain Text는 다운로드는 없어서 전체복사로 저장하면 되고요.

오디오는
m4b(오디오북 특화 파일, 북마크 기능 지원)
MP3(일반적 오디오 파일)
OGG(오픈소스)
spx(음성 전송 최적화?)

일단은 EPUB3이랑 Plain Text, 그리고 m4b로 받는 게 좋겠다고 생각만 했습니다.
몇개 다운로드 하긴 했는데, 이 부분 논의하고 나중에 다운로드 해도 될 것 같아서 잠시 미뤄뒀습니다.

**Comment by jasonheesanglee** [comment]
저는 일단 txt로 올리고 있습니다!
